// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package proto

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsNotebookserverNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == NotebookServerErrorReason_NOTEBOOKSERVER_NOT_FOUND.String() && e.Code == 404
}

func ErrorNotebookserverNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, NotebookServerErrorReason_NOTEBOOKSERVER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsNotebookserverValidateError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == NotebookServerErrorReason_NOTEBOOKSERVER_VALIDATE_ERROR.String() && e.Code == 400
}

func ErrorNotebookserverValidateError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, NotebookServerErrorReason_NOTEBOOKSERVER_VALIDATE_ERROR.String(), fmt.Sprintf(format, args...))
}
