// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: internal/context/notebookserver/interface/grpc/proto/notebookserver.proto

package proto

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotebookServerErrorReason int32

const (
	NotebookServerErrorReason_NOTEBOOKSERVER_NOT_FOUND      NotebookServerErrorReason = 0
	NotebookServerErrorReason_NOTEBOOKSERVER_VALIDATE_ERROR NotebookServerErrorReason = 1
)

// Enum value maps for NotebookServerErrorReason.
var (
	NotebookServerErrorReason_name = map[int32]string{
		0: "NOTEBOOKSERVER_NOT_FOUND",
		1: "NOTEBOOKSERVER_VALIDATE_ERROR",
	}
	NotebookServerErrorReason_value = map[string]int32{
		"NOTEBOOKSERVER_NOT_FOUND":      0,
		"NOTEBOOKSERVER_VALIDATE_ERROR": 1,
	}
)

func (x NotebookServerErrorReason) Enum() *NotebookServerErrorReason {
	p := new(NotebookServerErrorReason)
	*p = x
	return p
}

func (x NotebookServerErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotebookServerErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_enumTypes[0].Descriptor()
}

func (NotebookServerErrorReason) Type() protoreflect.EnumType {
	return &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_enumTypes[0]
}

func (x NotebookServerErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotebookServerErrorReason.Descriptor instead.
func (NotebookServerErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{0}
}

type GPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model  string  `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Card   float64 `protobuf:"fixed64,2,opt,name=card,proto3" json:"card,omitempty"`
	Memory int64   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *GPU) Reset() {
	*x = GPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{0}
}

func (x *GPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPU) GetCard() float64 {
	if x != nil {
		return x.Card
	}
	return 0
}

func (x *GPU) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type ResourceSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    float64 `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory int64   `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk   int64   `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Gpu    *GPU    `protobuf:"bytes,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *ResourceSize) Reset() {
	*x = ResourceSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSize) ProtoMessage() {}

func (x *ResourceSize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSize.ProtoReflect.Descriptor instead.
func (*ResourceSize) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSize) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceSize) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ResourceSize) GetDisk() int64 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *ResourceSize) GetGpu() *GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type CreateNotebookServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspaceID  string        `protobuf:"bytes,1,opt,name=workspaceID,proto3" json:"workspaceID,omitempty"`
	Image        string        `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ResourceSize *ResourceSize `protobuf:"bytes,3,opt,name=resourceSize,proto3" json:"resourceSize,omitempty"`
}

func (x *CreateNotebookServerRequest) Reset() {
	*x = CreateNotebookServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotebookServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotebookServerRequest) ProtoMessage() {}

func (x *CreateNotebookServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotebookServerRequest.ProtoReflect.Descriptor instead.
func (*CreateNotebookServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotebookServerRequest) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

func (x *CreateNotebookServerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateNotebookServerRequest) GetResourceSize() *ResourceSize {
	if x != nil {
		return x.ResourceSize
	}
	return nil
}

type CreateNotebookServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateNotebookServerResponse) Reset() {
	*x = CreateNotebookServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotebookServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotebookServerResponse) ProtoMessage() {}

func (x *CreateNotebookServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotebookServerResponse.ProtoReflect.Descriptor instead.
func (*CreateNotebookServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotebookServerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotebookServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspaceID string `protobuf:"bytes,1,opt,name=workspaceID,proto3" json:"workspaceID,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Notebook    string `protobuf:"bytes,3,opt,name=notebook,proto3" json:"notebook,omitempty"`
}

func (x *GetNotebookServerRequest) Reset() {
	*x = GetNotebookServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotebookServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookServerRequest) ProtoMessage() {}

func (x *GetNotebookServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookServerRequest.ProtoReflect.Descriptor instead.
func (*GetNotebookServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotebookServerRequest) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

func (x *GetNotebookServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNotebookServerRequest) GetNotebook() string {
	if x != nil {
		return x.Notebook
	}
	return ""
}

type GetNotebookServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image        string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ResourceSize *ResourceSize          `protobuf:"bytes,3,opt,name=resourceSize,proto3" json:"resourceSize,omitempty"`
	Status       string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	AccessURL    string                 `protobuf:"bytes,7,opt,name=accessURL,proto3" json:"accessURL,omitempty"`
}

func (x *GetNotebookServerResponse) Reset() {
	*x = GetNotebookServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotebookServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookServerResponse) ProtoMessage() {}

func (x *GetNotebookServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookServerResponse.ProtoReflect.Descriptor instead.
func (*GetNotebookServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotebookServerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNotebookServerResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetNotebookServerResponse) GetResourceSize() *ResourceSize {
	if x != nil {
		return x.ResourceSize
	}
	return nil
}

func (x *GetNotebookServerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNotebookServerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetNotebookServerResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetNotebookServerResponse) GetAccessURL() string {
	if x != nil {
		return x.AccessURL
	}
	return ""
}

type ListNotebookServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspaceID string `protobuf:"bytes,1,opt,name=workspaceID,proto3" json:"workspaceID,omitempty"`
}

func (x *ListNotebookServersRequest) Reset() {
	*x = ListNotebookServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotebookServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotebookServersRequest) ProtoMessage() {}

func (x *ListNotebookServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotebookServersRequest.ProtoReflect.Descriptor instead.
func (*ListNotebookServersRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotebookServersRequest) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

type NotebookServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image        string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ResourceSize *ResourceSize          `protobuf:"bytes,3,opt,name=resourceSize,proto3" json:"resourceSize,omitempty"`
	Status       string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *NotebookServer) Reset() {
	*x = NotebookServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotebookServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookServer) ProtoMessage() {}

func (x *NotebookServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookServer.ProtoReflect.Descriptor instead.
func (*NotebookServer) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{7}
}

func (x *NotebookServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotebookServer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *NotebookServer) GetResourceSize() *ResourceSize {
	if x != nil {
		return x.ResourceSize
	}
	return nil
}

func (x *NotebookServer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotebookServer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotebookServer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListNotebookServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*NotebookServer `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ListNotebookServersResponse) Reset() {
	*x = ListNotebookServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotebookServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotebookServersResponse) ProtoMessage() {}

func (x *ListNotebookServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotebookServersResponse.ProtoReflect.Descriptor instead.
func (*ListNotebookServersResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{8}
}

func (x *ListNotebookServersResponse) GetItems() []*NotebookServer {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateNotebookServerSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image        string        `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ResourceSize *ResourceSize `protobuf:"bytes,3,opt,name=resourceSize,proto3" json:"resourceSize,omitempty"`
}

func (x *UpdateNotebookServerSettingsRequest) Reset() {
	*x = UpdateNotebookServerSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotebookServerSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotebookServerSettingsRequest) ProtoMessage() {}

func (x *UpdateNotebookServerSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotebookServerSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotebookServerSettingsRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNotebookServerSettingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNotebookServerSettingsRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateNotebookServerSettingsRequest) GetResourceSize() *ResourceSize {
	if x != nil {
		return x.ResourceSize
	}
	return nil
}

type UpdateNotebookServerSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNotebookServerSettingsResponse) Reset() {
	*x = UpdateNotebookServerSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotebookServerSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotebookServerSettingsResponse) ProtoMessage() {}

func (x *UpdateNotebookServerSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotebookServerSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotebookServerSettingsResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{10}
}

type DeleteNotebookServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteNotebookServerRequest) Reset() {
	*x = DeleteNotebookServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotebookServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotebookServerRequest) ProtoMessage() {}

func (x *DeleteNotebookServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotebookServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotebookServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNotebookServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNotebookServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNotebookServerResponse) Reset() {
	*x = DeleteNotebookServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotebookServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotebookServerResponse) ProtoMessage() {}

func (x *DeleteNotebookServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotebookServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotebookServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{12}
}

type SwitchNotebookServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Onoff bool   `protobuf:"varint,2,opt,name=onoff,proto3" json:"onoff,omitempty"`
}

func (x *SwitchNotebookServerRequest) Reset() {
	*x = SwitchNotebookServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchNotebookServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchNotebookServerRequest) ProtoMessage() {}

func (x *SwitchNotebookServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchNotebookServerRequest.ProtoReflect.Descriptor instead.
func (*SwitchNotebookServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{13}
}

func (x *SwitchNotebookServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SwitchNotebookServerRequest) GetOnoff() bool {
	if x != nil {
		return x.Onoff
	}
	return false
}

type SwitchNotebookServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SwitchNotebookServerResponse) Reset() {
	*x = SwitchNotebookServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchNotebookServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchNotebookServerResponse) ProtoMessage() {}

func (x *SwitchNotebookServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchNotebookServerResponse.ProtoReflect.Descriptor instead.
func (*SwitchNotebookServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP(), []int{14}
}

var File_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto protoreflect.FileDescriptor

var file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDesc = []byte{
	0x0a, 0x49, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x03, 0x47, 0x50, 0x55, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x22, 0x6a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x69, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x12,
	0x1c, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x50, 0x55, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0x8e, 0x01,
	0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2e,
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x68,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0xa4, 0x02, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x55, 0x52, 0x4c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x55, 0x52, 0x4c, 0x22,
	0x3e, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22,
	0xfb, 0x01, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4a, 0x0a,
	0x1b, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x23, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x26, 0x0a, 0x24, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f,
	0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x1b, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x6e, 0x6f, 0x66, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6f, 0x6e, 0x6f, 0x66, 0x66, 0x22, 0x1e, 0x0a, 0x1c,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x6e, 0x0a, 0x19,
	0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x18, 0x4e, 0x4f, 0x54,
	0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x27, 0x0a,
	0x1d, 0x4e, 0x4f, 0x54, 0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x32, 0xf5, 0x04, 0x0a,
	0x15, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f,
	0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x61, 0x0a, 0x14, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x65, 0x62,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x65,
	0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65,
	0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescOnce sync.Once
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescData = file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDesc
)

func file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescGZIP() []byte {
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescOnce.Do(func() {
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescData)
	})
	return file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDescData
}

var file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_goTypes = []interface{}{
	(NotebookServerErrorReason)(0),               // 0: proto.NotebookServerErrorReason
	(*GPU)(nil),                                  // 1: proto.GPU
	(*ResourceSize)(nil),                         // 2: proto.ResourceSize
	(*CreateNotebookServerRequest)(nil),          // 3: proto.CreateNotebookServerRequest
	(*CreateNotebookServerResponse)(nil),         // 4: proto.CreateNotebookServerResponse
	(*GetNotebookServerRequest)(nil),             // 5: proto.GetNotebookServerRequest
	(*GetNotebookServerResponse)(nil),            // 6: proto.GetNotebookServerResponse
	(*ListNotebookServersRequest)(nil),           // 7: proto.ListNotebookServersRequest
	(*NotebookServer)(nil),                       // 8: proto.NotebookServer
	(*ListNotebookServersResponse)(nil),          // 9: proto.ListNotebookServersResponse
	(*UpdateNotebookServerSettingsRequest)(nil),  // 10: proto.UpdateNotebookServerSettingsRequest
	(*UpdateNotebookServerSettingsResponse)(nil), // 11: proto.UpdateNotebookServerSettingsResponse
	(*DeleteNotebookServerRequest)(nil),          // 12: proto.DeleteNotebookServerRequest
	(*DeleteNotebookServerResponse)(nil),         // 13: proto.DeleteNotebookServerResponse
	(*SwitchNotebookServerRequest)(nil),          // 14: proto.SwitchNotebookServerRequest
	(*SwitchNotebookServerResponse)(nil),         // 15: proto.SwitchNotebookServerResponse
	(*timestamppb.Timestamp)(nil),                // 16: google.protobuf.Timestamp
}
var file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_depIdxs = []int32{
	1,  // 0: proto.ResourceSize.gpu:type_name -> proto.GPU
	2,  // 1: proto.CreateNotebookServerRequest.resourceSize:type_name -> proto.ResourceSize
	2,  // 2: proto.GetNotebookServerResponse.resourceSize:type_name -> proto.ResourceSize
	16, // 3: proto.GetNotebookServerResponse.createdAt:type_name -> google.protobuf.Timestamp
	16, // 4: proto.GetNotebookServerResponse.updatedAt:type_name -> google.protobuf.Timestamp
	2,  // 5: proto.NotebookServer.resourceSize:type_name -> proto.ResourceSize
	16, // 6: proto.NotebookServer.createdAt:type_name -> google.protobuf.Timestamp
	16, // 7: proto.NotebookServer.updatedAt:type_name -> google.protobuf.Timestamp
	8,  // 8: proto.ListNotebookServersResponse.Items:type_name -> proto.NotebookServer
	2,  // 9: proto.UpdateNotebookServerSettingsRequest.resourceSize:type_name -> proto.ResourceSize
	3,  // 10: proto.NotebookServerService.CreateNotebookServer:input_type -> proto.CreateNotebookServerRequest
	5,  // 11: proto.NotebookServerService.GetNotebookServer:input_type -> proto.GetNotebookServerRequest
	10, // 12: proto.NotebookServerService.UpdateNotebookServerSettings:input_type -> proto.UpdateNotebookServerSettingsRequest
	12, // 13: proto.NotebookServerService.DeleteNotebookServer:input_type -> proto.DeleteNotebookServerRequest
	14, // 14: proto.NotebookServerService.SwitchNotebookServer:input_type -> proto.SwitchNotebookServerRequest
	7,  // 15: proto.NotebookServerService.ListNotebookServers:input_type -> proto.ListNotebookServersRequest
	4,  // 16: proto.NotebookServerService.CreateNotebookServer:output_type -> proto.CreateNotebookServerResponse
	6,  // 17: proto.NotebookServerService.GetNotebookServer:output_type -> proto.GetNotebookServerResponse
	11, // 18: proto.NotebookServerService.UpdateNotebookServerSettings:output_type -> proto.UpdateNotebookServerSettingsResponse
	13, // 19: proto.NotebookServerService.DeleteNotebookServer:output_type -> proto.DeleteNotebookServerResponse
	15, // 20: proto.NotebookServerService.SwitchNotebookServer:output_type -> proto.SwitchNotebookServerResponse
	9,  // 21: proto.NotebookServerService.ListNotebookServers:output_type -> proto.ListNotebookServersResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_init() }
func file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_init() {
	if File_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotebookServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotebookServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotebookServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotebookServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotebookServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotebookServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotebookServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotebookServerSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotebookServerSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotebookServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotebookServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchNotebookServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchNotebookServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_goTypes,
		DependencyIndexes: file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_depIdxs,
		EnumInfos:         file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_enumTypes,
		MessageInfos:      file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_msgTypes,
	}.Build()
	File_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto = out.File
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_rawDesc = nil
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_goTypes = nil
	file_internal_context_notebookserver_interface_grpc_proto_notebookserver_proto_depIdxs = nil
}
