// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: internal/context/workspace/interface/grpc/proto/errors.proto

package proto

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_WORKSPACE_NOT_FOUND    ErrorReason = 0
	ErrorReason_WORKSPACE_NAME_INVALID ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "WORKSPACE_NOT_FOUND",
		1: "WORKSPACE_NAME_INVALID",
	}
	ErrorReason_value = map[string]int32{
		"WORKSPACE_NOT_FOUND":    0,
		"WORKSPACE_NAME_INVALID": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_context_workspace_interface_grpc_proto_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_internal_context_workspace_interface_grpc_proto_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescGZIP(), []int{0}
}

var File_internal_context_workspace_interface_grpc_proto_errors_proto protoreflect.FileDescriptor

var file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x54, 0x0a, 0x0b, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x13, 0x57, 0x4f, 0x52,
	0x4b, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x20, 0x0a, 0x16, 0x57, 0x4f, 0x52, 0x4b,
	0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescOnce sync.Once
	file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescData = file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDesc
)

func file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescGZIP() []byte {
	file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescOnce.Do(func() {
		file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescData)
	})
	return file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDescData
}

var file_internal_context_workspace_interface_grpc_proto_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_context_workspace_interface_grpc_proto_errors_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: proto.ErrorReason
}
var file_internal_context_workspace_interface_grpc_proto_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_context_workspace_interface_grpc_proto_errors_proto_init() }
func file_internal_context_workspace_interface_grpc_proto_errors_proto_init() {
	if File_internal_context_workspace_interface_grpc_proto_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_context_workspace_interface_grpc_proto_errors_proto_goTypes,
		DependencyIndexes: file_internal_context_workspace_interface_grpc_proto_errors_proto_depIdxs,
		EnumInfos:         file_internal_context_workspace_interface_grpc_proto_errors_proto_enumTypes,
	}.Build()
	File_internal_context_workspace_interface_grpc_proto_errors_proto = out.File
	file_internal_context_workspace_interface_grpc_proto_errors_proto_rawDesc = nil
	file_internal_context_workspace_interface_grpc_proto_errors_proto_goTypes = nil
	file_internal_context_workspace_interface_grpc_proto_errors_proto_depIdxs = nil
}
