// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package proto

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsWorkspaceNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WORKSPACE_NOT_FOUND.String() && e.Code == 404
}

func ErrorWorkspaceNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_WORKSPACE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsWorkspaceNameInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WORKSPACE_NAME_INVALID.String() && e.Code == 400
}

func ErrorWorkspaceNameInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_WORKSPACE_NAME_INVALID.String(), fmt.Sprintf(format, args...))
}
