// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package proto

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsSubmissionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SubmissionErrorReason_SUBMISSION_NOT_FOUND.String() && e.Code == 404
}

func ErrorSubmissionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, SubmissionErrorReason_SUBMISSION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsSubmissionValidateError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SubmissionErrorReason_SUBMISSION_VALIDATE_ERROR.String() && e.Code == 404
}

func ErrorSubmissionValidateError(format string, args ...interface{}) *errors.Error {
	return errors.New(404, SubmissionErrorReason_SUBMISSION_VALIDATE_ERROR.String(), fmt.Sprintf(format, args...))
}
